package com.example.notepad.ui

import com.example.notepad.data.AppLanguage

data class UiText(
    val appName: String,
    val settings: String,
    val notesTab: String,
    val premium: String,
    val premiumAnnual: String,
    val premiumMonthly: String,
    val premiumAnnualOriginalPrice: String,
    val premiumAnnualPrice: String,
    val premiumMonthlyPrice: String,
    val premiumSubscribePending: String,
    val premiumTrial: String,
    val premiumRenewal: String,
    val privacyPolicy: String,
    val termsOfService: String,
    val premiumFeatures: String,
    val premiumFolders: String,
    val premiumFoldersBody: String,
    val premiumTextFormatting: String,
    val premiumTextFormattingBody: String,
    val premiumIcons: String,
    val premiumIconsBody: String,
    val premiumGrammar: String,
    val premiumGrammarBody: String,
    val premiumWritingAssistant: String,
    val premiumWritingAssistantBody: String,
    val premiumBillingUnavailable: String,
    val premiumActive: String,
    val premiumSubscribe: String,
    val premiumRestore: String,
    val language: String,
    val allNotes: String,
    val all: String,
    val activeNotes: String,
    val trash: String,
    val uncategorized: String,
    val search: String,
    val searchPlaceholder: String,
    val sortBy: String,
    val sortUpdated: String,
    val sortCreated: String,
    val sortTitle: String,
    val recentlyUpdated: String,
    val noteType: String,
    val allTypes: String,
    val textNotes: String,
    val drawingNotes: String,
    val checklistNotes: String,
    val reminderFilter: String,
    val allReminders: String,
    val withReminder: String,
    val hasReminder: String,
    val overdueReminders: String,
    val upcomingReminders: String,
    val listView: String,
    val calendarView: String,
    val reminderCalendar: String,
    val previousMonth: String,
    val nextMonth: String,
    val today: String,
    val noRemindersOnSelectedDay: String,
    val newTextNote: String,
    val newDrawingNote: String,
    val newChecklistNote: String,
    val ocrFromImage: String,
    val recognizingText: String,
    val ocrNoText: String,
    val ocrFailed: String,
    val ocrNoteDefaultTitle: String,
    val newFolder: String,
    val renameFolder: String,
    val deleteFolder: String,
    val delete: String,
    val deleteSelected: String,
    val moveToTrash: String,
    val rename: String,
    val restore: String,
    val permanentlyDelete: String,
    val noNotes: String,
    val noSearchResults: String,
    val noSearchOrFilterResults: String,
    val noDeletedNotes: String,
    val drawing: String,
    val text: String,
    val checklist: String,
    val pinned: String,
    val pin: String,
    val unpin: String,
    val updated: String,
    val created: String,
    val move: String,
    val edit: String,
    val more: String,
    val focusWriting: String,
    val exitFocusWriting: String,
    val fullscreenWriting: String,
    val details: String,
    val checkboxItem: String,
    val bulletItem: String,
    val hideKeyboard: String,
    val noteOptions: String,
    val textNote: String,
    val drawingNote: String,
    val checklistNote: String,
    val textEditor: String,
    val editorFontSize: String,
    val fontSmall: String,
    val fontMedium: String,
    val fontLarge: String,
    val saving: String,
    val saved: String,
    val lastUpdated: String,
    val reminder: String,
    val setReminder: String,
    val clearReminder: String,
    val reminderRepeat: String,
    val reminderRepeatNone: String,
    val reminderRepeatDaily: String,
    val reminderRepeatWeekly: String,
    val reminderRepeatMonthly: String,
    val share: String,
    val export: String,
    val shareChooserTitle: String,
    val exportTxt: String,
    val sharePng: String,
    val exportPng: String,
    val exportComplete: String,
    val exportFailed: String,
    val pngExportComplete: String,
    val pngExportFailed: String,
    val pngShareFailed: String,
    val folder: String,
    val drawingNoteDataNotice: String,
    val sharedNoteDefaultTitle: String,
    val undo: String,
    val redo: String,
    val pen: String,
    val eraser: String,
    val brushSize: String,
    val penSize: String,
    val eraserSize: String,
    val eraserSizeHint: String,
    val thin: String,
    val smallSize: String,
    val medium: String,
    val thick: String,
    val largeSize: String,
    val brushColor: String,
    val black: String,
    val red: String,
    val blue: String,
    val green: String,
    val noReminder: String,
    val reminderOverdue: String,
    val reminderUpcoming: String,
    val reminderMustBeFuture: String,
    val back: String,
    val clear: String,
    val clearDrawing: String,
    val clearDrawingBody: String,
    val findInNote: String,
    val searchInNote: String,
    val previousMatch: String,
    val nextMatch: String,
    val noMatches: String,
    val clearSearch: String,
    val findHint: String,
    val noteNotFound: String,
    val title: String,
    val content: String,
    val deleteNote: String,
    val deleteNoteBody: String,
    val deleteSelectedNotes: String,
    val deleteSelectedNotesBody: String,
    val permanentlyDeleteNote: String,
    val permanentlyDeleteNoteBody: String,
    val permanentlyDeleteSelectedNotes: String,
    val permanentlyDeleteSelectedNotesBody: String,
    val folderName: String,
    val create: String,
    val save: String,
    val cancel: String,
    val moveNote: String,
    val folderNameRequired: String,
    val allNotesIsFilter: String,
    val uncategorizedIsReserved: String,
    val folderAlreadyExists: String,
    val untitledDrawing: String,
    val untitledTextNote: String,
    val untitledChecklist: String,
    val addChecklistItem: String,
    val deleteChecklistItem: String,
    val checkedItems: (Int, Int) -> String,
    val privacy: String,
    val hideReminderNotificationContent: String,
    val hideReminderNotificationContentBody: String,
    val requireDeviceUnlock: String,
    val requireDeviceUnlockBody: String,
    val deviceLockUnavailable: String,
    val unlockJustNotes: String,
    val unlockRequiredBody: String,
    val turnOffLock: String,
    val googleAccountSync: String,
    val googleAccountSyncHint: String,
    val googleAccountSyncConnectedHint: String,
    val signInWithGoogle: String,
    val signedInAs: String,
    val notSignedIn: String,
    val syncNow: String,
    val syncComplete: String,
    val syncConflict: String,
    val syncFailed: String,
    val syncStatus: String,
    val signOut: String,
    val signOutGoogleTitle: String,
    val signOutGoogleBody: String,
    val googleDriveBackup: String,
    val backupTargetHint: String,
    val batchExportNotes: String,
    val batchImportTextFiles: String,
    val batchExportComplete: String,
    val batchExportFailed: String,
    val batchImportComplete: (Int) -> String,
    val batchImportFailed: String,
    val lastBackup: String,
    val lastSync: String,
    val lastRestore: String,
    val backupInProgress: String,
    val restoreInProgress: String,
    val restoreBackupConfirmTitle: String,
    val restoreBackupConfirmBody: String,
    val restoreRollbackAvailable: String,
    val undoRestore: String,
    val restoreRollbackComplete: String,
    val restoreRollbackFailed: String,
    val backupToGoogleDrive: String,
    val restoreFromBackup: String,
    val backupComplete: String,
    val restoreComplete: String,
    val backupFailed: String,
    val restoreFailed: String,
    val onlineSyncProvider: String,
    val onlineSyncTargetConnected: String,
    val onlineSyncTargetMissing: String,
    val syncNotes: String,
    val autoSyncOnStart: String,
    val chooseGoogleDriveSyncFile: String,
    val changeGoogleDriveSyncFile: String,
    val accountSettings: String,
    val disconnectSync: String,
    val disconnectSyncTitle: String,
    val disconnectSyncBody: String,
    val syncTarget: String,
    val thisDevice: String,
    val connectedDevices: String,
    val googleDriveHandledByFiles: String,
) {
    fun resultCount(count: Int): String {
        return if (this === TraditionalChineseText) {
            "$count 筆結果"
        } else {
            "$count results"
        }
    }

    fun deleteFolderBody(folderName: String): String {
        return if (this === TraditionalChineseText) {
            "$folderName 裡的記事會移到 $uncategorized。"
        } else {
            "Notes in $folderName will move to $uncategorized."
        }
    }

    fun selectedNotesCount(count: Int): String {
        return if (this === TraditionalChineseText) {
            "已選 $count 筆"
        } else {
            "$count selected"
        }
    }

    fun syncNotesCount(count: Int): String {
        return "$syncNotes $count"
    }

    fun signedInAsAccount(email: String): String {
        return "$signedInAs $email"
    }

    fun remindersOnDate(count: Int): String {
        return if (this === TraditionalChineseText) {
            "$count 則提醒"
        } else {
            "$count reminders"
        }
    }

    fun addReminderLabel(): String {
        return if (this === TraditionalChineseText) "新增提醒" else "Add reminder"
    }

    fun reminderPresetMorningLabel(): String {
        return if (this === TraditionalChineseText) "上午 09:00" else "Morning 09:00"
    }

    fun reminderPresetAfternoonLabel(): String {
        return if (this === TraditionalChineseText) "下午 14:00" else "Afternoon 14:00"
    }

    fun reminderPresetEveningLabel(): String {
        return if (this === TraditionalChineseText) "晚上 18:00" else "Evening 18:00"
    }

    fun reminderPresetNextHourLabel(): String {
        return if (this === TraditionalChineseText) "下一小時" else "Next hour"
    }

    fun previousDayLabel(): String {
        return if (this === TraditionalChineseText) "前一天" else "Previous day"
    }

    fun nextDayLabel(): String {
        return if (this === TraditionalChineseText) "下一天" else "Next day"
    }

    fun reminderNotificationsBlockedLabel(): String {
        return if (this === TraditionalChineseText) {
            "請開啟通知才能使用提醒。"
        } else {
            "Turn on notifications to use reminders."
        }
    }
}

val EnglishText = UiText(
    appName = "Just Notes",
    settings = "Settings",
    notesTab = "Notes",
    premium = "Premium",
    premiumAnnual = "Annual",
    premiumMonthly = "Monthly",
    premiumAnnualOriginalPrice = "",
    premiumAnnualPrice = "Price not available",
    premiumMonthlyPrice = "Price not available",
    premiumSubscribePending = "Subscribe (setup pending)",
    premiumTrial = "No trial or introductory offer is configured.",
    premiumRenewal = "Prices appear after Google Play products are configured. Production unlock requires backend verification.",
    privacyPolicy = "Privacy Policy",
    termsOfService = "Terms of Service",
    premiumFeatures = "Premium features",
    premiumFolders = "Folders",
    premiumFoldersBody = "Premium will provide folder organization for grouping notes by topic and switching between them quickly.",
    premiumTextFormatting = "Text formatting",
    premiumTextFormattingBody = "Premium will provide headings, bold, italic, underline, links, and highlight formatting for richer notes.",
    premiumIcons = "Reminder/calendar tools",
    premiumIconsBody = "Premium includes reminder and calendar tools for planning around notes.",
    premiumGrammar = "Checklist notes",
    premiumGrammarBody = "Structured checklist notes are available for real task tracking, not just checkbox text.",
    premiumWritingAssistant = "Writing assistant",
    premiumWritingAssistantBody = "Draft cleanup, summaries, and smarter rewrite tools are planned after the trust baseline.",
    premiumBillingUnavailable = "Google Play Billing is not connected yet.",
    premiumActive = "Premium active",
    premiumSubscribe = "Subscribe",
    premiumRestore = "Restore purchase status",
    language = "Language",
    allNotes = "All Notes",
    all = "All",
    activeNotes = "Notes",
    trash = "Trash",
    uncategorized = "Uncategorized",
    search = "Search",
    searchPlaceholder = "Search title or note content",
    sortBy = "Sort",
    sortUpdated = "Updated time",
    sortCreated = "Created time",
    sortTitle = "Title",
    recentlyUpdated = "Recently updated",
    noteType = "Type",
    allTypes = "All types",
    textNotes = "Text notes",
    drawingNotes = "Drawing notes",
    checklistNotes = "Checklist notes",
    reminderFilter = "Reminder",
    allReminders = "All reminders",
    withReminder = "With reminder",
    hasReminder = "Has reminder",
    overdueReminders = "Overdue",
    upcomingReminders = "Upcoming",
    listView = "List",
    calendarView = "Calendar",
    reminderCalendar = "Reminder calendar",
    previousMonth = "Previous month",
    nextMonth = "Next month",
    today = "Today",
    noRemindersOnSelectedDay = "No reminders on this day",
    newTextNote = "New Text Note",
    newDrawingNote = "New Drawing Note",
    newChecklistNote = "New Checklist",
    ocrFromImage = "Scan text from image",
    recognizingText = "Recognizing text...",
    ocrNoText = "No text was recognized in this image.",
    ocrFailed = "OCR failed. Try another image.",
    ocrNoteDefaultTitle = "OCR Note",
    newFolder = "New Folder",
    renameFolder = "Rename Folder",
    deleteFolder = "Delete Folder",
    delete = "Delete",
    deleteSelected = "Delete",
    moveToTrash = "Move to Trash",
    rename = "Rename",
    restore = "Restore",
    permanentlyDelete = "Delete forever",
    noNotes = "No notes",
    noSearchResults = "No matching notes",
    noSearchOrFilterResults = "No notes match this search or filter",
    noDeletedNotes = "Trash is empty",
    drawing = "Drawing",
    text = "Text",
    checklist = "Checklist",
    pinned = "Pinned",
    pin = "Pin",
    unpin = "Unpin",
    updated = "Updated",
    created = "Created",
    move = "Move",
    edit = "Edit",
    more = "More",
    focusWriting = "Full screen",
    exitFocusWriting = "Done",
    fullscreenWriting = "Full-screen writing",
    details = "Details",
    checkboxItem = "Checkbox",
    bulletItem = "Bullet",
    hideKeyboard = "Hide keyboard",
    noteOptions = "Note options",
    textNote = "Text Note",
    drawingNote = "Drawing Note",
    checklistNote = "Checklist Note",
    textEditor = "Text Editor",
    editorFontSize = "Editor font size",
    fontSmall = "Small",
    fontMedium = "Medium",
    fontLarge = "Large",
    saving = "Saving...",
    saved = "Saved",
    lastUpdated = "Last updated",
    reminder = "Reminder",
    setReminder = "Set reminder",
    clearReminder = "Clear reminder",
    reminderRepeat = "Repeat",
    reminderRepeatNone = "Does not repeat",
    reminderRepeatDaily = "Daily",
    reminderRepeatWeekly = "Weekly",
    reminderRepeatMonthly = "Monthly",
    share = "Share",
    export = "Export",
    shareChooserTitle = "Share note",
    exportTxt = "Export .txt",
    sharePng = "Share PNG",
    exportPng = "Export PNG",
    exportComplete = "Text file exported.",
    exportFailed = "Text export failed.",
    pngExportComplete = "PNG exported.",
    pngExportFailed = "PNG export failed.",
    pngShareFailed = "PNG share failed.",
    folder = "Folder",
    drawingNoteDataNotice = "Drawing note data is stored in app.",
    sharedNoteDefaultTitle = "Shared Note",
    undo = "Undo",
    redo = "Redo",
    pen = "Pen",
    eraser = "Eraser",
    brushSize = "Size",
    penSize = "Pen size",
    eraserSize = "Eraser size",
    eraserSizeHint = "Eraser clears a square using the selected size.",
    thin = "Thin",
    smallSize = "Small",
    medium = "Medium",
    thick = "Thick",
    largeSize = "Large",
    brushColor = "Color",
    black = "Black",
    red = "Red",
    blue = "Blue",
    green = "Green",
    noReminder = "No reminder",
    reminderOverdue = "Overdue",
    reminderUpcoming = "Upcoming",
    reminderMustBeFuture = "Reminder must be in the future.",
    back = "Back",
    clear = "Clear",
    clearDrawing = "Clear drawing",
    clearDrawingBody = "This removes every stroke from this drawing note.",
    findInNote = "Find in note",
    searchInNote = "Search in note",
    previousMatch = "Previous match",
    nextMatch = "Next match",
    noMatches = "No matches",
    clearSearch = "Clear search",
    findHint = "Type to find in this note",
    noteNotFound = "Note not found",
    title = "Title",
    content = "Content",
    deleteNote = "Delete Note",
    deleteNoteBody = "This note will move to Trash.",
    deleteSelectedNotes = "Move selected notes to Trash",
    deleteSelectedNotesBody = "Selected notes will move to Trash.",
    permanentlyDeleteNote = "Delete Note Forever",
    permanentlyDeleteNoteBody = "This note will be permanently removed from this device.",
    permanentlyDeleteSelectedNotes = "Delete selected notes forever",
    permanentlyDeleteSelectedNotesBody = "Selected notes will be permanently removed from this device.",
    folderName = "Folder name",
    create = "Create",
    save = "Save",
    cancel = "Cancel",
    moveNote = "Move Note",
    folderNameRequired = "Folder name is required.",
    allNotesIsFilter = "All Notes is a filter.",
    uncategorizedIsReserved = "Uncategorized is reserved.",
    folderAlreadyExists = "Folder already exists.",
    untitledDrawing = "Untitled drawing",
    untitledTextNote = "Untitled text note",
    untitledChecklist = "Untitled checklist",
    addChecklistItem = "Add item",
    deleteChecklistItem = "Delete item",
    checkedItems = { checked, total -> "$checked/$total checked" },
    privacy = "Privacy",
    hideReminderNotificationContent = "Hide reminder notification content",
    hideReminderNotificationContentBody = "Notifications show only a generic reminder, not the note title or content.",
    requireDeviceUnlock = "Lock Just Notes",
    requireDeviceUnlockBody = "Require Android device unlock before showing notes.",
    deviceLockUnavailable = "Set a screen lock in Android Settings to use this.",
    unlockJustNotes = "Unlock Just Notes",
    unlockRequiredBody = "Confirm your Android screen lock to view your notes.",
    turnOffLock = "Turn off lock",
    googleAccountSync = "Google Account Sync",
    googleAccountSyncHint = "Sign in to sync notes through your Google account using private Google Drive app data. Local notes stay on this device when you sign out.",
    googleAccountSyncConnectedHint = "Google sync is connected on this device. You can sync now or sign out; local notes stay on this device.",
    signInWithGoogle = "Sign in with Google",
    signedInAs = "Signed in as",
    notSignedIn = "Not signed in",
    syncNow = "Sync now",
    syncComplete = "Sync complete.",
    syncConflict = "Conflict copy created.",
    syncFailed = "Sync failed.",
    syncStatus = "Sync status",
    signOut = "Sign out",
    signOutGoogleTitle = "Sign out of Google sync?",
    signOutGoogleBody = "This disconnects Google sync on this device. Local notes stay on this device.",
    googleDriveBackup = "Backup & Restore",
    backupTargetHint = "Save or restore a manual JSON backup through Android's file picker. You choose where the backup file is stored.",
    batchExportNotes = "Export notes ZIP",
    batchImportTextFiles = "Import text files",
    batchExportComplete = "Notes ZIP exported.",
    batchExportFailed = "Notes ZIP export failed.",
    batchImportComplete = { count -> "$count text files imported." },
    batchImportFailed = "Text file import failed.",
    lastBackup = "Last backup",
    lastSync = "Last sync",
    lastRestore = "Last restore",
    backupInProgress = "Backing up...",
    restoreInProgress = "Restoring...",
    restoreBackupConfirmTitle = "Restore backup?",
    restoreBackupConfirmBody = "Choose a trusted backup file. Restore replaces all current local notes and folders with the selected backup.",
    restoreRollbackAvailable = "Restore checkpoint saved privately on this device. You can undo the last restore until another restore runs or you undo it.",
    undoRestore = "Undo restore",
    restoreRollbackComplete = "Restore undone.",
    restoreRollbackFailed = "Undo restore failed.",
    backupToGoogleDrive = "Save backup",
    restoreFromBackup = "Restore backup",
    backupComplete = "Backup saved.",
    restoreComplete = "Backup restored.",
    backupFailed = "Backup failed.",
    restoreFailed = "Restore failed.",
    onlineSyncProvider = "Android file picker",
    onlineSyncTargetConnected = "Backup file selected",
    onlineSyncTargetMissing = "No backup file selected",
    syncNotes = "Notes to back up:",
    autoSyncOnStart = "Overwrite the backup file when the app opens",
    chooseGoogleDriveSyncFile = "Choose backup file",
    changeGoogleDriveSyncFile = "Change backup file",
    accountSettings = "Backup details",
    disconnectSync = "Forget file",
    disconnectSyncTitle = "Forget backup file?",
    disconnectSyncBody = "This removes the saved backup destination from this device. Local notes stay on this device.",
    syncTarget = "Backup target",
    thisDevice = "This device",
    connectedDevices = "Device",
    googleDriveHandledByFiles = "This screen saves and restores manual JSON backups through Android's file picker.",
)

val TraditionalChineseText = UiText(
    appName = "本機記事",
    settings = "設定",
    notesTab = "記事",
    premium = "進階",
    premiumAnnual = "年方案",
    premiumMonthly = "月方案",
    premiumAnnualOriginalPrice = "",
    premiumAnnualPrice = "價格尚未開放",
    premiumMonthlyPrice = "價格尚未開放",
    premiumSubscribePending = "訂閱（準備中）",
    premiumTrial = "目前未設定試用或優惠方案。",
    premiumRenewal = "價格會在 Google Play 商品設定完成後顯示；正式解鎖需要後端驗證。",
    privacyPolicy = "隱私權政策",
    termsOfService = "服務條款",
    premiumFeatures = "進階功能",
    premiumFolders = "資料夾",
    premiumFoldersBody = "進階版會提供資料夾分類，方便依主題整理記事並快速切換。",
    premiumTextFormatting = "文字格式",
    premiumTextFormattingBody = "進階版會提供標題、粗體、斜體、底線、連結與螢光標記等文字格式。",
    premiumIcons = "提醒／日曆工具",
    premiumIconsBody = "進階版包含圍繞記事安排事項的提醒與日曆工具。",
    premiumGrammar = "清單記事",
    premiumGrammarBody = "已支援真正結構化的清單記事，而不只是文字核取方塊。",
    premiumWritingAssistant = "寫作輔助",
    premiumWritingAssistantBody = "草稿整理、摘要與更智慧的改寫工具會在信任基礎完成後導入。",
    premiumBillingUnavailable = "尚未連接 Google Play Billing。",
    premiumActive = "進階版已啟用",
    premiumSubscribe = "訂閱",
    premiumRestore = "更新購買狀態",
    language = "語言",
    allNotes = "全部記事",
    all = "全部",
    activeNotes = "一般記事",
    trash = "垃圾桶",
    uncategorized = "未分類",
    search = "搜尋",
    searchPlaceholder = "搜尋標題或記事內容",
    sortBy = "排序",
    sortUpdated = "更新時間",
    sortCreated = "建立時間",
    sortTitle = "標題",
    recentlyUpdated = "最近修改",
    noteType = "類型",
    allTypes = "全部類型",
    textNotes = "文字記事",
    drawingNotes = "繪圖記事",
    checklistNotes = "清單記事",
    reminderFilter = "提醒",
    allReminders = "全部提醒",
    withReminder = "有提醒",
    hasReminder = "有提醒",
    overdueReminders = "已過期",
    upcomingReminders = "即將到期",
    listView = "列表",
    calendarView = "日曆",
    reminderCalendar = "提醒日曆",
    previousMonth = "上個月",
    nextMonth = "下個月",
    today = "今天",
    noRemindersOnSelectedDay = "這一天沒有提醒",
    newTextNote = "新增文字記事",
    newDrawingNote = "新增繪圖記事",
    newChecklistNote = "新增清單",
    ocrFromImage = "從圖片辨識文字",
    recognizingText = "正在辨識文字...",
    ocrNoText = "這張圖片沒有辨識到文字。",
    ocrFailed = "OCR 辨識失敗，請換一張圖片再試。",
    ocrNoteDefaultTitle = "OCR 筆記",
    newFolder = "新增資料夾",
    renameFolder = "重新命名資料夾",
    deleteFolder = "刪除資料夾",
    delete = "刪除",
    deleteSelected = "刪除",
    moveToTrash = "移到垃圾桶",
    rename = "重新命名",
    restore = "還原",
    permanentlyDelete = "永久刪除",
    noNotes = "沒有記事",
    noSearchResults = "沒有符合的記事",
    noSearchOrFilterResults = "沒有符合搜尋或篩選的記事",
    noDeletedNotes = "垃圾桶是空的",
    drawing = "繪圖",
    text = "文字",
    checklist = "清單",
    pinned = "已置頂",
    pin = "置頂",
    unpin = "取消置頂",
    updated = "更新",
    created = "建立",
    move = "移動",
    edit = "編輯",
    more = "更多",
    focusWriting = "全螢幕",
    exitFocusWriting = "完成",
    fullscreenWriting = "全螢幕書寫",
    details = "詳細",
    checkboxItem = "核取方塊",
    bulletItem = "項目符號",
    hideKeyboard = "隱藏鍵盤",
    noteOptions = "記事選項",
    textNote = "文字記事",
    drawingNote = "繪圖記事",
    checklistNote = "清單記事",
    textEditor = "文字編輯器",
    editorFontSize = "編輯器字體大小",
    fontSmall = "小",
    fontMedium = "中",
    fontLarge = "大",
    saving = "儲存中...",
    saved = "已儲存",
    lastUpdated = "最後更新",
    reminder = "提醒",
    setReminder = "設定提醒",
    clearReminder = "清除提醒",
    reminderRepeat = "重複",
    reminderRepeatNone = "不重複",
    reminderRepeatDaily = "每天",
    reminderRepeatWeekly = "每週",
    reminderRepeatMonthly = "每月",
    share = "分享",
    export = "匯出",
    shareChooserTitle = "分享記事",
    exportTxt = "匯出 .txt",
    sharePng = "分享 PNG",
    exportPng = "匯出 PNG",
    exportComplete = "文字檔已匯出。",
    exportFailed = "文字匯出失敗。",
    pngExportComplete = "PNG 已匯出。",
    pngExportFailed = "PNG 匯出失敗。",
    pngShareFailed = "PNG 分享失敗。",
    folder = "資料夾",
    drawingNoteDataNotice = "繪圖記事資料儲存在 App 內。",
    sharedNoteDefaultTitle = "分享記事",
    undo = "復原",
    redo = "重做",
    pen = "筆",
    eraser = "橡皮擦",
    brushSize = "大小",
    penSize = "筆刷大小",
    eraserSize = "橡皮擦大小",
    eraserSizeHint = "橡皮擦會用目前大小的方塊真正清除像素。",
    thin = "細",
    smallSize = "小",
    medium = "中",
    thick = "粗",
    largeSize = "大",
    brushColor = "顏色",
    black = "黑",
    red = "紅",
    blue = "藍",
    green = "綠",
    noReminder = "沒有提醒",
    reminderOverdue = "已過期",
    reminderUpcoming = "即將到期",
    reminderMustBeFuture = "提醒時間必須在未來。",
    back = "返回",
    clear = "清除",
    clearDrawing = "清除繪圖",
    clearDrawingBody = "這會移除此繪圖記事中的所有筆畫。",
    findInNote = "在記事內搜尋",
    searchInNote = "在記事內搜尋",
    previousMatch = "上一筆",
    nextMatch = "下一筆",
    noMatches = "無符合結果",
    clearSearch = "清除搜尋",
    findHint = "輸入文字以搜尋這則記事",
    noteNotFound = "找不到記事",
    title = "標題",
    content = "內容",
    deleteNote = "刪除記事",
    deleteNoteBody = "這則記事會移到垃圾桶。",
    deleteSelectedNotes = "將所選記事移到垃圾桶",
    deleteSelectedNotesBody = "所選記事會移到垃圾桶。",
    permanentlyDeleteNote = "永久刪除記事",
    permanentlyDeleteNoteBody = "這則記事會從此裝置永久移除。",
    permanentlyDeleteSelectedNotes = "永久刪除所選記事",
    permanentlyDeleteSelectedNotesBody = "所選記事會從此裝置永久移除。",
    folderName = "資料夾名稱",
    create = "建立",
    save = "儲存",
    cancel = "取消",
    moveNote = "移動記事",
    folderNameRequired = "請輸入資料夾名稱。",
    allNotesIsFilter = "全部記事是篩選器。",
    uncategorizedIsReserved = "未分類是保留名稱。",
    folderAlreadyExists = "資料夾已存在。",
    untitledDrawing = "未命名繪圖",
    untitledTextNote = "未命名文字記事",
    untitledChecklist = "未命名清單",
    addChecklistItem = "新增項目",
    deleteChecklistItem = "刪除項目",
    checkedItems = { checked, total -> "$checked/$total 已完成" },
    privacy = "隱私",
    hideReminderNotificationContent = "隱藏提醒通知內容",
    hideReminderNotificationContentBody = "通知只顯示一般提醒，不顯示記事標題或內容。",
    requireDeviceUnlock = "鎖定 Just Notes",
    requireDeviceUnlockBody = "顯示記事前，需要先通過 Android 裝置解鎖。",
    deviceLockUnavailable = "請先在 Android 設定中設定螢幕鎖定。",
    unlockJustNotes = "解鎖 Just Notes",
    unlockRequiredBody = "請確認 Android 螢幕鎖定後查看記事。",
    turnOffLock = "關閉鎖定",
    googleAccountSync = "Google 帳號同步",
    googleAccountSyncHint = "登入後會透過你的 Google 帳號使用私有 Google Drive app data 同步記事。登出時，本機記事不會被刪除。",
    googleAccountSyncConnectedHint = "此裝置已連接 Google 同步。你可以立即同步或登出；本機記事不會被刪除。",
    signInWithGoogle = "使用 Google 登入",
    signedInAs = "已登入",
    notSignedIn = "尚未登入",
    syncNow = "立即同步",
    syncComplete = "同步完成。",
    syncConflict = "已建立衝突副本。",
    syncFailed = "同步失敗。",
    syncStatus = "同步狀態",
    signOut = "登出",
    signOutGoogleTitle = "登出 Google 同步？",
    signOutGoogleBody = "這會中斷此裝置的 Google 同步。本機記事不會被刪除。",
    googleDriveBackup = "備份與還原",
    backupTargetHint = "透過 Android 檔案選擇器儲存或還原手動 JSON 備份。備份檔由你選擇並保存。",
    batchExportNotes = "匯出記事 ZIP",
    batchImportTextFiles = "匯入文字檔",
    batchExportComplete = "記事 ZIP 已匯出。",
    batchExportFailed = "記事 ZIP 匯出失敗。",
    batchImportComplete = { count -> "已匯入 $count 個文字檔。" },
    batchImportFailed = "文字檔匯入失敗。",
    lastBackup = "上次備份",
    lastSync = "上次同步",
    lastRestore = "上次還原",
    backupInProgress = "備份中...",
    restoreInProgress = "還原中...",
    restoreBackupConfirmTitle = "還原備份？",
    restoreBackupConfirmBody = "請選擇可信任的備份檔。還原會用所選備份取代目前所有本機記事與資料夾。",
    restoreRollbackAvailable = "還原檢查點已安全儲存在此裝置。再次還原或復原前，都可以復原上次還原。",
    undoRestore = "復原這次還原",
    restoreRollbackComplete = "已復原這次還原。",
    restoreRollbackFailed = "復原還原失敗。",
    backupToGoogleDrive = "儲存備份",
    restoreFromBackup = "還原備份",
    backupComplete = "備份已儲存。",
    restoreComplete = "備份已還原。",
    backupFailed = "備份失敗。",
    restoreFailed = "還原失敗。",
    onlineSyncProvider = "Android 檔案選擇器",
    onlineSyncTargetConnected = "已選擇備份檔",
    onlineSyncTargetMissing = "尚未選擇備份檔",
    syncNotes = "將備份記事：",
    autoSyncOnStart = "開啟 app 時覆寫備份檔",
    chooseGoogleDriveSyncFile = "選擇備份檔",
    changeGoogleDriveSyncFile = "更換備份檔",
    accountSettings = "備份詳細資訊",
    disconnectSync = "忘記檔案",
    disconnectSyncTitle = "忘記備份檔？",
    disconnectSyncBody = "這會移除此裝置保存的備份目的地。本機記事不會被刪除。",
    syncTarget = "備份目標",
    thisDevice = "這台裝置",
    connectedDevices = "裝置",
    googleDriveHandledByFiles = "此畫面只透過 Android 檔案選擇器儲存與還原手動 JSON 備份。",
)

fun uiTextFor(language: AppLanguage): UiText {
    return when (language) {
        AppLanguage.English -> EnglishText
        AppLanguage.TraditionalChinese -> TraditionalChineseText
    }
}
