package com.example.notepad.ui

import com.example.notepad.data.AppLanguage

data class UiText(
    val appName: String,
    val settings: String,
    val language: String,
    val allNotes: String,
    val all: String,
    val activeNotes: String,
    val trash: String,
    val uncategorized: String,
    val search: String,
    val searchPlaceholder: String,
    val sortBy: String,
    val sortUpdated: String,
    val sortCreated: String,
    val sortTitle: String,
    val recentlyUpdated: String,
    val noteType: String,
    val allTypes: String,
    val textNotes: String,
    val drawingNotes: String,
    val reminderFilter: String,
    val allReminders: String,
    val withReminder: String,
    val hasReminder: String,
    val overdueReminders: String,
    val upcomingReminders: String,
    val newTextNote: String,
    val newDrawingNote: String,
    val ocrFromImage: String,
    val recognizingText: String,
    val ocrNoText: String,
    val ocrFailed: String,
    val ocrNoteDefaultTitle: String,
    val newFolder: String,
    val renameFolder: String,
    val deleteFolder: String,
    val delete: String,
    val deleteSelected: String,
    val moveToTrash: String,
    val rename: String,
    val restore: String,
    val permanentlyDelete: String,
    val noNotes: String,
    val noSearchResults: String,
    val noSearchOrFilterResults: String,
    val noDeletedNotes: String,
    val drawing: String,
    val text: String,
    val pinned: String,
    val pin: String,
    val unpin: String,
    val updated: String,
    val created: String,
    val move: String,
    val edit: String,
    val more: String,
    val focusWriting: String,
    val exitFocusWriting: String,
    val fullscreenWriting: String,
    val details: String,
    val checkboxItem: String,
    val bulletItem: String,
    val hideKeyboard: String,
    val noteOptions: String,
    val textNote: String,
    val drawingNote: String,
    val textEditor: String,
    val editorFontSize: String,
    val fontSmall: String,
    val fontMedium: String,
    val fontLarge: String,
    val saving: String,
    val saved: String,
    val lastUpdated: String,
    val reminder: String,
    val setReminder: String,
    val clearReminder: String,
    val share: String,
    val export: String,
    val shareChooserTitle: String,
    val exportTxt: String,
    val sharePng: String,
    val exportPng: String,
    val exportComplete: String,
    val exportFailed: String,
    val pngExportComplete: String,
    val pngExportFailed: String,
    val pngShareFailed: String,
    val folder: String,
    val drawingNoteDataNotice: String,
    val sharedNoteDefaultTitle: String,
    val undo: String,
    val redo: String,
    val pen: String,
    val eraser: String,
    val brushSize: String,
    val penSize: String,
    val eraserSize: String,
    val eraserSizeHint: String,
    val thin: String,
    val smallSize: String,
    val medium: String,
    val thick: String,
    val largeSize: String,
    val brushColor: String,
    val black: String,
    val red: String,
    val blue: String,
    val green: String,
    val noReminder: String,
    val reminderOverdue: String,
    val reminderUpcoming: String,
    val reminderMustBeFuture: String,
    val back: String,
    val clear: String,
    val clearDrawing: String,
    val clearDrawingBody: String,
    val findInNote: String,
    val searchInNote: String,
    val previousMatch: String,
    val nextMatch: String,
    val noMatches: String,
    val clearSearch: String,
    val findHint: String,
    val noteNotFound: String,
    val title: String,
    val content: String,
    val deleteNote: String,
    val deleteNoteBody: String,
    val deleteSelectedNotes: String,
    val deleteSelectedNotesBody: String,
    val permanentlyDeleteNote: String,
    val permanentlyDeleteNoteBody: String,
    val permanentlyDeleteSelectedNotes: String,
    val permanentlyDeleteSelectedNotesBody: String,
    val folderName: String,
    val create: String,
    val save: String,
    val cancel: String,
    val moveNote: String,
    val folderNameRequired: String,
    val allNotesIsFilter: String,
    val uncategorizedIsReserved: String,
    val folderAlreadyExists: String,
    val untitledDrawing: String,
    val untitledTextNote: String,
    val googleDriveBackup: String,
    val backupTargetHint: String,
    val lastBackup: String,
    val lastRestore: String,
    val backupInProgress: String,
    val restoreInProgress: String,
    val restoreBackupConfirmTitle: String,
    val restoreBackupConfirmBody: String,
    val backupToGoogleDrive: String,
    val restoreFromBackup: String,
    val backupComplete: String,
    val restoreComplete: String,
    val backupFailed: String,
    val restoreFailed: String,
) {
    fun resultCount(count: Int): String {
        return if (this === TraditionalChineseText) {
            "$count 筆結果"
        } else {
            "$count results"
        }
    }

    fun deleteFolderBody(folderName: String): String {
        return if (this === TraditionalChineseText) {
            "$folderName 裡的記事會移到 $uncategorized。"
        } else {
            "Notes in $folderName will move to $uncategorized."
        }
    }

    fun selectedNotesCount(count: Int): String {
        return if (this === TraditionalChineseText) {
            "已選 $count 筆"
        } else {
            "$count selected"
        }
    }
}

val EnglishText = UiText(
    appName = "Claw Notes",
    settings = "Settings",
    language = "Language",
    allNotes = "All Notes",
    all = "All",
    activeNotes = "Notes",
    trash = "Trash",
    uncategorized = "Uncategorized",
    search = "Search",
    searchPlaceholder = "Search title or note content",
    sortBy = "Sort",
    sortUpdated = "Updated time",
    sortCreated = "Created time",
    sortTitle = "Title",
    recentlyUpdated = "Recently updated",
    noteType = "Type",
    allTypes = "All types",
    textNotes = "Text notes",
    drawingNotes = "Drawing notes",
    reminderFilter = "Reminder",
    allReminders = "All reminders",
    withReminder = "With reminder",
    hasReminder = "Has reminder",
    overdueReminders = "Overdue",
    upcomingReminders = "Upcoming",
    newTextNote = "New Text Note",
    newDrawingNote = "New Drawing Note",
    ocrFromImage = "Scan text from image",
    recognizingText = "Recognizing text...",
    ocrNoText = "No text was recognized in this image.",
    ocrFailed = "OCR failed. Try another image.",
    ocrNoteDefaultTitle = "OCR Note",
    newFolder = "New Folder",
    renameFolder = "Rename Folder",
    deleteFolder = "Delete Folder",
    delete = "Delete",
    deleteSelected = "Delete",
    moveToTrash = "Move to Trash",
    rename = "Rename",
    restore = "Restore",
    permanentlyDelete = "Delete forever",
    noNotes = "No notes",
    noSearchResults = "No matching notes",
    noSearchOrFilterResults = "No notes match this search or filter",
    noDeletedNotes = "Trash is empty",
    drawing = "Drawing",
    text = "Text",
    pinned = "Pinned",
    pin = "Pin",
    unpin = "Unpin",
    updated = "Updated",
    created = "Created",
    move = "Move",
    edit = "Edit",
    more = "More",
    focusWriting = "Full screen",
    exitFocusWriting = "Done",
    fullscreenWriting = "Full-screen writing",
    details = "Details",
    checkboxItem = "Checkbox",
    bulletItem = "Bullet",
    hideKeyboard = "Hide keyboard",
    noteOptions = "Note options",
    textNote = "Text Note",
    drawingNote = "Drawing Note",
    textEditor = "Text Editor",
    editorFontSize = "Editor font size",
    fontSmall = "Small",
    fontMedium = "Medium",
    fontLarge = "Large",
    saving = "Saving...",
    saved = "Saved",
    lastUpdated = "Last updated",
    reminder = "Reminder",
    setReminder = "Set reminder",
    clearReminder = "Clear reminder",
    share = "Share",
    export = "Export",
    shareChooserTitle = "Share note",
    exportTxt = "Export .txt",
    sharePng = "Share PNG",
    exportPng = "Export PNG",
    exportComplete = "Text file exported.",
    exportFailed = "Text export failed.",
    pngExportComplete = "PNG exported.",
    pngExportFailed = "PNG export failed.",
    pngShareFailed = "PNG share failed.",
    folder = "Folder",
    drawingNoteDataNotice = "Drawing note data is stored in app.",
    sharedNoteDefaultTitle = "Shared Note",
    undo = "Undo",
    redo = "Redo",
    pen = "Pen",
    eraser = "Eraser",
    brushSize = "Size",
    penSize = "Pen size",
    eraserSize = "Eraser size",
    eraserSizeHint = "Eraser clears a square using the selected size.",
    thin = "Thin",
    smallSize = "Small",
    medium = "Medium",
    thick = "Thick",
    largeSize = "Large",
    brushColor = "Color",
    black = "Black",
    red = "Red",
    blue = "Blue",
    green = "Green",
    noReminder = "No reminder",
    reminderOverdue = "Overdue",
    reminderUpcoming = "Upcoming",
    reminderMustBeFuture = "Reminder must be in the future.",
    back = "Back",
    clear = "Clear",
    clearDrawing = "Clear drawing",
    clearDrawingBody = "This removes every stroke from this drawing note.",
    findInNote = "Find in note",
    searchInNote = "Search in note",
    previousMatch = "Previous match",
    nextMatch = "Next match",
    noMatches = "No matches",
    clearSearch = "Clear search",
    findHint = "Type to find in this note",
    noteNotFound = "Note not found",
    title = "Title",
    content = "Content",
    deleteNote = "Delete Note",
    deleteNoteBody = "This note will move to Trash.",
    deleteSelectedNotes = "Move selected notes to Trash",
    deleteSelectedNotesBody = "Selected notes will move to Trash.",
    permanentlyDeleteNote = "Delete Note Forever",
    permanentlyDeleteNoteBody = "This note will be permanently removed from this device.",
    permanentlyDeleteSelectedNotes = "Delete selected notes forever",
    permanentlyDeleteSelectedNotesBody = "Selected notes will be permanently removed from this device.",
    folderName = "Folder name",
    create = "Create",
    save = "Save",
    cancel = "Cancel",
    moveNote = "Move Note",
    folderNameRequired = "Folder name is required.",
    allNotesIsFilter = "All Notes is a filter.",
    uncategorizedIsReserved = "Uncategorized is reserved.",
    folderAlreadyExists = "Folder already exists.",
    untitledDrawing = "Untitled drawing",
    untitledTextNote = "Untitled text note",
    googleDriveBackup = "Google Drive Backup",
    backupTargetHint = "Choose a Google Drive folder or local file from the Android file picker. Restore replaces all local notes and folders with the selected backup.",
    lastBackup = "Last backup",
    lastRestore = "Last restore",
    backupInProgress = "Backing up...",
    restoreInProgress = "Restoring...",
    restoreBackupConfirmTitle = "Restore backup?",
    restoreBackupConfirmBody = "Choose a trusted backup file. Restore replaces all current local notes and folders with the selected backup.",
    backupToGoogleDrive = "Back Up",
    restoreFromBackup = "Restore",
    backupComplete = "Backup saved.",
    restoreComplete = "Backup restored.",
    backupFailed = "Backup failed.",
    restoreFailed = "Restore failed.",
)

val TraditionalChineseText = UiText(
    appName = "本機記事",
    settings = "設定",
    language = "語言",
    allNotes = "全部記事",
    all = "全部",
    activeNotes = "一般記事",
    trash = "垃圾桶",
    uncategorized = "未分類",
    search = "搜尋",
    searchPlaceholder = "搜尋標題或記事內容",
    sortBy = "排序",
    sortUpdated = "更新時間",
    sortCreated = "建立時間",
    sortTitle = "標題",
    recentlyUpdated = "最近修改",
    noteType = "類型",
    allTypes = "全部類型",
    textNotes = "文字記事",
    drawingNotes = "繪圖記事",
    reminderFilter = "提醒",
    allReminders = "全部提醒",
    withReminder = "有提醒",
    hasReminder = "有提醒",
    overdueReminders = "已過期",
    upcomingReminders = "即將到期",
    newTextNote = "新增文字記事",
    newDrawingNote = "新增繪圖記事",
    ocrFromImage = "從圖片辨識文字",
    recognizingText = "正在辨識文字...",
    ocrNoText = "這張圖片沒有辨識到文字。",
    ocrFailed = "OCR 辨識失敗，請換一張圖片再試。",
    ocrNoteDefaultTitle = "OCR 筆記",
    newFolder = "新增資料夾",
    renameFolder = "重新命名資料夾",
    deleteFolder = "刪除資料夾",
    delete = "刪除",
    deleteSelected = "刪除",
    moveToTrash = "移到垃圾桶",
    rename = "重新命名",
    restore = "還原",
    permanentlyDelete = "永久刪除",
    noNotes = "沒有記事",
    noSearchResults = "沒有符合的記事",
    noSearchOrFilterResults = "沒有符合搜尋或篩選的記事",
    noDeletedNotes = "垃圾桶是空的",
    drawing = "繪圖",
    text = "文字",
    pinned = "已置頂",
    pin = "置頂",
    unpin = "取消置頂",
    updated = "更新",
    created = "建立",
    move = "移動",
    edit = "編輯",
    more = "更多",
    focusWriting = "全螢幕",
    exitFocusWriting = "完成",
    fullscreenWriting = "全螢幕書寫",
    details = "詳細",
    checkboxItem = "核取方塊",
    bulletItem = "項目符號",
    hideKeyboard = "隱藏鍵盤",
    noteOptions = "記事選項",
    textNote = "文字記事",
    drawingNote = "繪圖記事",
    textEditor = "文字編輯器",
    editorFontSize = "編輯器字體大小",
    fontSmall = "小",
    fontMedium = "中",
    fontLarge = "大",
    saving = "儲存中...",
    saved = "已儲存",
    lastUpdated = "最後更新",
    reminder = "提醒",
    setReminder = "設定提醒",
    clearReminder = "清除提醒",
    share = "分享",
    export = "匯出",
    shareChooserTitle = "分享記事",
    exportTxt = "匯出 .txt",
    sharePng = "分享 PNG",
    exportPng = "匯出 PNG",
    exportComplete = "文字檔已匯出。",
    exportFailed = "文字匯出失敗。",
    pngExportComplete = "PNG 已匯出。",
    pngExportFailed = "PNG 匯出失敗。",
    pngShareFailed = "PNG 分享失敗。",
    folder = "資料夾",
    drawingNoteDataNotice = "繪圖記事資料儲存在 App 內。",
    sharedNoteDefaultTitle = "分享記事",
    undo = "復原",
    redo = "重做",
    pen = "筆",
    eraser = "橡皮擦",
    brushSize = "大小",
    penSize = "筆刷大小",
    eraserSize = "橡皮擦大小",
    eraserSizeHint = "橡皮擦會用目前大小的方塊真正清除像素。",
    thin = "細",
    smallSize = "小",
    medium = "中",
    thick = "粗",
    largeSize = "大",
    brushColor = "顏色",
    black = "黑",
    red = "紅",
    blue = "藍",
    green = "綠",
    noReminder = "沒有提醒",
    reminderOverdue = "已過期",
    reminderUpcoming = "即將到期",
    reminderMustBeFuture = "提醒時間必須在未來。",
    back = "返回",
    clear = "清除",
    clearDrawing = "清除繪圖",
    clearDrawingBody = "這會移除此繪圖記事中的所有筆畫。",
    findInNote = "在記事內搜尋",
    searchInNote = "在記事內搜尋",
    previousMatch = "上一筆",
    nextMatch = "下一筆",
    noMatches = "無符合結果",
    clearSearch = "清除搜尋",
    findHint = "輸入文字以搜尋這則記事",
    noteNotFound = "找不到記事",
    title = "標題",
    content = "內容",
    deleteNote = "刪除記事",
    deleteNoteBody = "這則記事會移到垃圾桶。",
    deleteSelectedNotes = "將所選記事移到垃圾桶",
    deleteSelectedNotesBody = "所選記事會移到垃圾桶。",
    permanentlyDeleteNote = "永久刪除記事",
    permanentlyDeleteNoteBody = "這則記事會從此裝置永久移除。",
    permanentlyDeleteSelectedNotes = "永久刪除所選記事",
    permanentlyDeleteSelectedNotesBody = "所選記事會從此裝置永久移除。",
    folderName = "資料夾名稱",
    create = "建立",
    save = "儲存",
    cancel = "取消",
    moveNote = "移動記事",
    folderNameRequired = "請輸入資料夾名稱。",
    allNotesIsFilter = "全部記事是篩選器。",
    uncategorizedIsReserved = "未分類是保留名稱。",
    folderAlreadyExists = "資料夾已存在。",
    untitledDrawing = "未命名繪圖",
    untitledTextNote = "未命名文字記事",
    googleDriveBackup = "Google Drive 備份",
    backupTargetHint = "從 Android 檔案選擇器挑選 Google Drive 資料夾或本機檔案。還原會用所選備份取代目前所有本機記事與資料夾。",
    lastBackup = "上次備份",
    lastRestore = "上次還原",
    backupInProgress = "備份中...",
    restoreInProgress = "還原中...",
    restoreBackupConfirmTitle = "還原備份？",
    restoreBackupConfirmBody = "請選擇可信任的備份檔。還原會用所選備份取代目前所有本機記事與資料夾。",
    backupToGoogleDrive = "備份",
    restoreFromBackup = "還原",
    backupComplete = "備份已儲存。",
    restoreComplete = "備份已還原。",
    backupFailed = "備份失敗。",
    restoreFailed = "還原失敗。",
)

fun uiTextFor(language: AppLanguage): UiText {
    return when (language) {
        AppLanguage.English -> EnglishText
        AppLanguage.TraditionalChinese -> TraditionalChineseText
    }
}
