package com.example.notepad.ui

import com.example.notepad.data.AppLanguage

data class UiText(
    val appName: String,
    val settings: String,
    val language: String,
    val allNotes: String,
    val activeNotes: String,
    val trash: String,
    val uncategorized: String,
    val search: String,
    val searchPlaceholder: String,
    val sortBy: String,
    val sortUpdated: String,
    val sortCreated: String,
    val sortTitle: String,
    val noteType: String,
    val allTypes: String,
    val textNotes: String,
    val drawingNotes: String,
    val newTextNote: String,
    val newDrawingNote: String,
    val newFolder: String,
    val renameFolder: String,
    val deleteFolder: String,
    val delete: String,
    val rename: String,
    val restore: String,
    val permanentlyDelete: String,
    val noNotes: String,
    val noSearchResults: String,
    val noDeletedNotes: String,
    val drawing: String,
    val text: String,
    val pinned: String,
    val pin: String,
    val unpin: String,
    val updated: String,
    val created: String,
    val move: String,
    val textNote: String,
    val drawingNote: String,
    val back: String,
    val clear: String,
    val noteNotFound: String,
    val title: String,
    val content: String,
    val deleteNote: String,
    val deleteNoteBody: String,
    val permanentlyDeleteNote: String,
    val permanentlyDeleteNoteBody: String,
    val folderName: String,
    val save: String,
    val cancel: String,
    val moveNote: String,
    val folderNameRequired: String,
    val allNotesIsFilter: String,
    val uncategorizedIsReserved: String,
    val folderAlreadyExists: String,
    val untitledDrawing: String,
    val untitledTextNote: String,
    val googleDriveBackup: String,
    val backupToGoogleDrive: String,
    val restoreFromBackup: String,
    val backupComplete: String,
    val restoreComplete: String,
    val backupFailed: String,
    val restoreFailed: String,
) {
    fun deleteFolderBody(folderName: String): String {
        return if (this === TraditionalChineseText) {
            "$folderName 裡的記事會移到 $uncategorized。"
        } else {
            "Notes in $folderName will move to $uncategorized."
        }
    }
}

val EnglishText = UiText(
    appName = "Local Notepad",
    settings = "Settings",
    language = "Language",
    allNotes = "All Notes",
    activeNotes = "Notes",
    trash = "Trash",
    uncategorized = "Uncategorized",
    search = "Search",
    searchPlaceholder = "Search title or note content",
    sortBy = "Sort",
    sortUpdated = "Updated time",
    sortCreated = "Created time",
    sortTitle = "Title",
    noteType = "Type",
    allTypes = "All types",
    textNotes = "Text notes",
    drawingNotes = "Drawing notes",
    newTextNote = "New Text Note",
    newDrawingNote = "New Drawing Note",
    newFolder = "New Folder",
    renameFolder = "Rename Folder",
    deleteFolder = "Delete Folder",
    delete = "Delete",
    rename = "Rename",
    restore = "Restore",
    permanentlyDelete = "Delete forever",
    noNotes = "No notes",
    noSearchResults = "No matching notes",
    noDeletedNotes = "Trash is empty",
    drawing = "Drawing",
    text = "Text",
    pinned = "Pinned",
    pin = "Pin",
    unpin = "Unpin",
    updated = "Updated",
    created = "Created",
    move = "Move",
    textNote = "Text Note",
    drawingNote = "Drawing Note",
    back = "Back",
    clear = "Clear",
    noteNotFound = "Note not found",
    title = "Title",
    content = "Content",
    deleteNote = "Delete Note",
    deleteNoteBody = "This note will move to Trash.",
    permanentlyDeleteNote = "Delete Note Forever",
    permanentlyDeleteNoteBody = "This note will be permanently removed from this device.",
    folderName = "Folder name",
    save = "Save",
    cancel = "Cancel",
    moveNote = "Move Note",
    folderNameRequired = "Folder name is required.",
    allNotesIsFilter = "All Notes is a filter.",
    uncategorizedIsReserved = "Uncategorized is reserved.",
    folderAlreadyExists = "Folder already exists.",
    untitledDrawing = "Untitled drawing",
    untitledTextNote = "Untitled text note",
    googleDriveBackup = "Google Drive Backup",
    backupToGoogleDrive = "Back Up",
    restoreFromBackup = "Restore",
    backupComplete = "Backup saved.",
    restoreComplete = "Backup restored.",
    backupFailed = "Backup failed.",
    restoreFailed = "Restore failed.",
)

val TraditionalChineseText = UiText(
    appName = "本機記事",
    settings = "設定",
    language = "語言",
    allNotes = "全部記事",
    activeNotes = "一般記事",
    trash = "垃圾桶",
    uncategorized = "未分類",
    search = "搜尋",
    searchPlaceholder = "搜尋標題或記事內容",
    sortBy = "排序",
    sortUpdated = "更新時間",
    sortCreated = "建立時間",
    sortTitle = "標題",
    noteType = "類型",
    allTypes = "全部類型",
    textNotes = "文字記事",
    drawingNotes = "繪圖記事",
    newTextNote = "新增文字記事",
    newDrawingNote = "新增繪圖記事",
    newFolder = "新增資料夾",
    renameFolder = "重新命名資料夾",
    deleteFolder = "刪除資料夾",
    delete = "刪除",
    rename = "重新命名",
    restore = "還原",
    permanentlyDelete = "永久刪除",
    noNotes = "沒有記事",
    noSearchResults = "沒有符合的記事",
    noDeletedNotes = "垃圾桶是空的",
    drawing = "繪圖",
    text = "文字",
    pinned = "已置頂",
    pin = "置頂",
    unpin = "取消置頂",
    updated = "更新",
    created = "建立",
    move = "移動",
    textNote = "文字記事",
    drawingNote = "繪圖記事",
    back = "返回",
    clear = "清除",
    noteNotFound = "找不到記事",
    title = "標題",
    content = "內容",
    deleteNote = "刪除記事",
    deleteNoteBody = "這則記事會移到垃圾桶。",
    permanentlyDeleteNote = "永久刪除記事",
    permanentlyDeleteNoteBody = "這則記事會從此裝置永久移除。",
    folderName = "資料夾名稱",
    save = "儲存",
    cancel = "取消",
    moveNote = "移動記事",
    folderNameRequired = "請輸入資料夾名稱。",
    allNotesIsFilter = "全部記事是篩選器。",
    uncategorizedIsReserved = "未分類是保留名稱。",
    folderAlreadyExists = "資料夾已存在。",
    untitledDrawing = "未命名繪圖",
    untitledTextNote = "未命名文字記事",
    googleDriveBackup = "Google Drive 備份",
    backupToGoogleDrive = "備份",
    restoreFromBackup = "還原",
    backupComplete = "備份已儲存。",
    restoreComplete = "備份已還原。",
    backupFailed = "備份失敗。",
    restoreFailed = "還原失敗。",
)

fun uiTextFor(language: AppLanguage): UiText {
    return when (language) {
        AppLanguage.English -> EnglishText
        AppLanguage.TraditionalChinese -> TraditionalChineseText
    }
}
